### ISSUE TITLE
What's the license? :eyes:

### ISSUE THREAD

**Issue by TheOddGarlic** [SorusClient/Sorus-Launcher#3]
As you might know if you don't specify a license, it is by default `Copyright © every single contributor, year` which means:

1. Forced warranty laws in some countries still apply.
2. Everyone who has contributed is a copyright holder.
3. This technically is not (free and) open source, it is instead source-available.

Now that everyone who has contributed is a copyright holder you need to ask them to change the license.

**Comment by Hot-Tutorials** [comment]
I will change this. Thanks for telling me
